# Generated by Django 3.2 on 2022-09-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
